# Generated by Django 4.2.13 on 2024-06-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="google_places_last_updated",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Google Places last date updated"
            ),
        ),
    ]
